### ISSUE TITLE
customizing buttons

### ISSUE THREAD

**Issue by elizabethyalkut** [aaronpinero/typography#1]
Customizing buttons is kind of a hassle/unintuitive. I settled on creating a @mixin campaign_button that extends .button and adds some customizations, but creating the reverse-variant on the button has only been a partial success, since there's a `border: none !important` in tyfy's `a[href].button`.

**Comment by aaronpinero** [comment]
I will shortly be releasing an update that will improve this. There will definitely get rid of the !important (that was a mistake on my part). I will also be adding a mixin for outlined buttons and making button border radius something that can be set in the mixin.
